import '../styles.css' // This should be the correct relative path
import Head from 'next/head'

export default function Page() {
  return (
    <div className="inner_page">
      <Head>
        <title>
          BNNGPT Terms of Service - Your Guide to Using Our AI-Powered Search
          Engine
        </title>
        <meta
          name="description"
          content="Read BNNGPT's Terms of Service to understand the rules and guidelines for using our AI-powered search engine."
        />
        <meta
          property="og:title"
          content="BNNGPT Terms of Service - Your Guide to Using Our AI-Powered Search Engine"
        />
        <meta
          property="og:description"
          content="Read BNNGPT's Terms of Service to understand the rules and guidelines for using our AI-powered search engine."
        />
        <meta
          property="og:url"
          content="https://www.bnngpt.com/terms-of-service"
        />
        <meta property="og:image" content="https://www.bnngpt.com/logo.jpg" />
        <meta property="og:site_name" content="BNNGPT" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="" />
        <meta name="twitter:creator" content="" />
        <meta
          name="twitter:title"
          content="BNNGPT Terms of Service - Your Guide to Using Our AI-Powered Search Engine"
        />
        <meta
          name="twitter:description"
          content="Read BNNGPT's Terms of Service to understand the rules and guidelines for using our AI-powered search engine."
        />
        <meta name="twitter:image" content="https://www.bnngpt.com/logo.jpg" />
      </Head>
      <a href="/" className="logo_div"></a>
      <h2>BNNGPT Terms of Service</h2>
      <p>Last updated: May 18th, 2024.</p>
      <p>
        Please read these Terms of Service (“Terms”, “Terms of Service”)
        carefully before using the{' '}
        <a href="http://www.bnngpt.com/">www.bnngpt.com</a> website (the
        “Service”) operated by BNNGPT (“us”, “we”, or “our”).
      </p>
      <p>
        Your access to and use of the Service is conditioned on your acceptance
        of and compliance with these Terms. These Terms apply to all visitors,
        users, and others who access or use the Service.
      </p>
      <p>
        By accessing or using the Service, you agree to be bound by these Terms.
        BNNGPT reserves the right, in its sole discretion, to restrict, suspend,
        or terminate your access to and use of the Service.
      </p>
      <h3>Our Services</h3>
      <p>
        BNNGPT, powered by ePiphany AI, provides advanced AI-powered search and
        text generation services. BNNGPT is available via{' '}
        <a href="http://www.bnngpt.com/">www.bnngpt.com</a> and other related
        internet domains.
      </p>
      <h3>Acceptable Use</h3>
      <p>
        You must be at least 13 years old to use the Service. If you are under
        18, you must have your parent or legal guardian’s permission to use the
        Service. You agree not to share, transfer, or sell your account. You are
        responsible for all activities on your account.
      </p>
      <p>
        You agree not to use the Service in any way that causes, or may cause,
        damage to the Service or impairment of the availability or accessibility
        of the Service. You agree not to use the Service for unlawful, illegal,
        fraudulent, or harmful activities, including but not limited to hate,
        harassment, violence, political manipulation, spam, or malware.
      </p>
      <p>
        You agree not to conduct any systematic or automated data collection
        activities (including scraping, data mining, data extraction, or data
        harvesting) on or in relation to the Service. Prohibited data collection
        includes, but is not limited to, using the Service as input into other
        services, websites, or databases. You agree not to republish any content
        generated by the Service without clearly citing the Service as well as
        the context associated with the content. Misrepresentation of the source
        of the content or the nature of its creation is strictly prohibited.
      </p>
      <h3>User-Generated Content</h3>
      <p>
        The Service may allow you to upload, submit, store, send, or receive
        content. You retain ownership of any intellectual property rights that
        you hold in that content. In short, what belongs to you stays yours.
      </p>
      <p>
        When you upload, submit, store, send, or receive content to or through
        the Service, you give us (and those we work with) a worldwide license to
        use, host, store, reproduce, modify, create derivative works (such as
        those resulting from translations, adaptations, or other changes we make
        so that your content works better with the Service), communicate,
        publish, publicly perform, publicly display, and distribute such
        content. The rights you grant in this license are for the limited
        purpose of operating, promoting, and improving our Service, and to
        develop new ones. Make sure you have the necessary rights to grant us
        this license for any content that you submit to our Services.
      </p>
      <p>
        You understand that all information, data, text, software, music, sound,
        photographs, graphics, video, messages, tags, or other materials
        (“Content”), whether publicly posted or privately transmitted, are the
        sole responsibility of the person from whom such Content originated.
        This means that you, and not BNNGPT, are entirely responsible for all
        Content that you upload, post, email, transmit, or otherwise make
        available via the Service. BNNGPT does not control the Content posted
        via the Service and, as such, does not guarantee the accuracy,
        integrity, or quality of such Content. You understand that by using the
        Service, you may be exposed to Content that is offensive, indecent, or
        objectionable. Under no circumstances will BNNGPT be liable in any way
        for any Content, including, but not limited to, any errors or omissions
        in any Content, or any loss or damage of any kind incurred as a result
        of the use of any Content posted, emailed, transmitted, or otherwise
        made available via the Service.
      </p>
      <p>
        You agree that you must evaluate and bear all risks associated with the
        use of any Content, including any reliance on the accuracy,
        completeness, or usefulness of such Content. In this regard, you
        acknowledge that you may not rely on any Content created by the Service
        or submitted to the Service.
      </p>
      <p>
        You acknowledge and agree that BNNGPT may preserve Content and may also
        disclose Content if required to do so by law.
      </p>
      <h3>Intellectual Property Rights</h3>
      <p>
        BNNGPT acknowledges and respects the intellectual property rights of all
        individuals and entities and expects all users of the Service to do the
        same. Any attempts to reverse engineer, copy, reproduce, or otherwise
        steal intellectual property from the Service will not be tolerated and
        may result in legal action.
      </p>
      <p>
        BNNGPT takes all allegations of copyright infringement seriously and
        will respond promptly to any notices that comply with applicable laws
        and are properly provided to us. If you believe that your work has been
        used in a manner that constitutes copyright infringement, please email
        us at <a href="mailto:support@bnngpt.com">support@bnngpt.com</a>.
      </p>
      <h3>Limitation of Liability</h3>
      <p>
        In no event shall BNNGPT, nor its directors, employees, partners,
        agents, suppliers, or affiliates, be liable for any indirect,
        incidental, special, consequential, or punitive damages, including
        without limitation, loss of profits, data, use, goodwill, or other
        intangible losses, resulting from (i) your access to or use of or
        inability to access or use the Service; (ii) any conduct or content of
        any third party on the Service; (iii) any content obtained from the
        Service; and (iv) unauthorized access, use, or alteration of your
        transmissions or content, whether based on warranty, contract, tort
        (including negligence) or any other legal theory, whether or not we have
        been informed of the possibility of such damage, and even if a remedy
        set forth herein is found to have failed of its essential purpose.
      </p>
      <h3>Disclaimer</h3>
      <p>
        Your use of the Service is at your sole risk. The Service is provided on
        an “AS IS” and “AS AVAILABLE” basis. The Service is provided without
        warranties of any kind, whether express or implied, including, but not
        limited to, implied warranties of merchantability, fitness for a
        particular purpose, non-infringement, or course of performance.
      </p>
      <p>
        BNNGPT, its subsidiaries, affiliates, and its licensors do not warrant
        that a) the Service will function uninterrupted, secure, or available at
        any particular time or location; b) any errors or defects will be
        corrected; c) the Service is free of viruses or other harmful
        components; nor d) the results of using the Service will meet your
        requirements.
      </p>
      <h3>Indemnification</h3>
      <p>
        You agree to defend, indemnify and hold harmless BNNGPT and its licensee
        and licensors, and their employees, contractors, agents, officers, and
        directors, from and against any and all claims, damages, obligations,
        losses, liabilities, costs or debt, and expenses (including but not
        limited to attorney’s fees), resulting from or arising out of a) your
        use and access of the Service, by you or any person using your account
        and password; b) a breach of these Terms; or c) Content posted on the
        Service.
      </p>
      <h3>Changes</h3>
      <p>
        We reserve the right, at our sole discretion, to modify or replace these
        Terms at any time. If a revision is material, we will try to provide at
        least 30 days notice prior to any new terms taking effect. What
        constitutes a material change will be determined at our sole discretion.
      </p>
      <p>
        After modification, we will post the revised Terms and update the “Last
        updated” date above. By continuing to access or use our Service after
        those revisions become effective, you agree to be bound by the revised
        terms. If you do not agree to the new terms, please cease using the
        Service.
      </p>
      <h3>Contact Us</h3>
      <p>
        If you have any questions about these Terms, please contact us at{' '}
        <a href="mailto:support@bnngpt.com">support@bnngpt.com</a>.
      </p>
    </div>
  )
}
