import TopBar from '@/components/TopBar'

export default function Page() {
  const sections = [
    {
      heading: 'Last updated: May 18th, 2024.',
      content: `This privacy policy (“Policy”) describes how www.bnngpt.com and associated websites (“BNNGPT,” “we,” “us,” or “our”) collect, use, share, and protect information about you when you use our website, products, and services (collectively, the “Services”). This Privacy Policy does not cover the BNNGPT API, which is subject to the terms outlined in the Data Processing Agreement.`
    },
    {
      heading: 'Our Services',
      content: `BNNGPT, powered by ePiphany AI, provides advanced AI-powered search and text generation services. BNNGPT is available viawww.bnngpt.com and other related internet domains.`
    },
    {
      heading: 'Why Use BNNGPT?',
      content: [
        'Precision and Accuracy: Our sophisticated algorithms ensure that you get precise answers, cutting through the noise to deliver exactly what you need.',
        'Human-like Interaction: BNNGPT offers a conversational search experience, making your interactions with the search engine feel natural and intuitive.',
        'Broad Applications: From everyday questions to complex research topics, BNNGPT is designed to handle a wide range of queries, supporting both casual users and professionals alike.',
        'Continuous Improvement: Our AI constantly learns and evolves, incorporating the latest advancements in AI research to stay ahead of the curve and provide you with the best possible service.'
      ]
    },
    {
      heading: 'Acceptable Use',
      content: (
        <>
          You must be at least 13 years old to use the Service. If you are under
          18, you must have your parent or legal guardian’s permission to use
          the Service. You agree not to share, transfer, or sell your account.
          You are responsible for all activities on your account.
          <br />
          <br />
          You agree not to use the Service in any way that causes, or may cause,
          damage to the Service or impairment of the availability or
          accessibility of the Service. You agree not to use the Service for
          unlawful, illegal, fraudulent, or harmful activities, including but
          not limited to hate, harassment, violence, political manipulation,
          spam, or malware.
          <br />
          <br />
          You agree not to conduct any systematic or automated data collection
          activities (including scraping, data mining, data extraction, or data
          harvesting) on or in relation to the Service. Prohibited data
          collection includes, but is not limited to, using the Service as input
          into other services, websites, or databases. You agree not to
          republish any content generated by the Service without clearly citing
          the Service as well as the context associated with the content.
          Misrepresentation of the source of the content or the nature of its
          creation is strictly prohibited.
        </>
      )
    },
    {
      heading: 'User-Generated Content',
      content: (
        <>
          The Service may allow you to upload, submit, store, send, or receive
          content. You retain ownership of any intellectual property rights that
          you hold in that content. In short, what belongs to you stays yours.
          <br />
          <br />
          When you upload, submit, store, send, or receive content to or through
          the Service, you give us (and those we work with) a worldwide license
          to use, host, store, reproduce, modify, create derivative works (such
          as those resulting from translations, adaptations, or other changes we
          make so that your content works better with the Service), communicate,
          publish, publicly perform, publicly display, and distribute such
          content. The rights you grant in this license are for the limited
          purpose of operating, promoting, and improving our Service, and to
          develop new ones. Make sure you have the necessary rights to grant us
          this license for any content that you submit to our Services.
          <br />
          <br />
          You understand that all information, data, text, software, music,
          sound, photographs, graphics, video, messages, tags, or other
          materials (“Content”), whether publicly posted or privately
          transmitted, are the sole responsibility of the person from whom such
          Content originated. This means that you, and not BNNGPT, are entirely
          responsible for all Content that you upload, post, email, transmit, or
          otherwise make available via the Service. BNNGPT does not control the
          Content posted via the Service and, as such, does not guarantee the
          accuracy, integrity, or quality of such Content. You understand that
          by using the Service, you may be exposed to Content that is offensive,
          indecent, or objectionable. Under no circumstances will BNNGPT be
          liable in any way for any Content, including, but not limited to, any
          errors or omissions in any Content, or any loss or damage of any kind
          incurred as a result of the use of any Content posted, emailed,
          transmitted, or otherwise made available via the Service.
          <br />
          <br />
          You agree that you must evaluate and bear all risks associated with
          the use of any Content, including any reliance on the accuracy,
          completeness, or usefulness of such Content. In this regard, you
          acknowledge that you may not rely on any Content created by the
          Service or submitted to the Service.
          <br />
          <br />
          You acknowledge and agree that BNNGPT may preserve Content and may
          also disclose Content if required to do so by law.
        </>
      )
    }
  ]

  return (
    <>
      <TopBar />
      <div className="min-h-screen bg-primary">
        <div className="max-w-3xl mx-auto py-12">
          {/* <h1 className="text-lg font-base mb-8 items-center">About Us</h1> */}
          {sections.map((section, index) => (
            <div
              key={index}
              className="mb-8 p-6 bg-results-foreground rounded-xl"
            >
              <h2 className="text-lg font-medium mb-4">{section.heading}</h2>
              {Array.isArray(section.content) ? (
                <ul className="list-disc pl-5 text-text-secondary text-sm">
                  {section.content.map((item, itemIndex) => (
                    <li key={itemIndex} className="mb-2">
                      {item}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="text-text-secondary text-sm">{section.content}</p>
              )}
            </div>
          ))}
        </div>
      </div>
    </>
  )
}
